### ISSUE TITLE
Updating via frontend causes broken editor

### ISSUE THREAD

**Issue by fluxxdog** [NetroScript/Graveyard-Keeper-Savefile-Editor#68]
Attempted to update via browser. Can no longer launch the program at all. I wipe everything, unzipped the 1.19 release again, and ran everything through a console. Got the following. Note that I do not have a J: drive.

D:\Games\Graveyard Keeper\Graveyard Keeper Savefile Editor>"Graveyard Keeper Savefile Editor.exe"
Looking for save files in the folder: C:\Users\xxxxxxx\AppData\LocalLow\Lazy Bear Games\Graveyard Keeper
Deleting Old Frontend (html folder)
Copying new frontend files
Deleting old locals.json
Copying new locals.json
Deleting old itemversion
Copying new itemversion
Finished updating - now closing
Traceback (most recent call last):
  File "J:\Programme\Python64\lib\site-packages\gevent\greenlet.py", line 536, in run
  File "J:\Programme\Python64\lib\site-packages\eel\__init__.py", line 191, in _process_message
  File "J:\Projekte\GitHub\Graveyard Keeper Savefile Editor\main.py", line 110, in updateitemversion
NameError: name 'exit' is not defined
Sun Nov  8 14:34:53 2020 <Greenlet at 0x1d52e089cc0: _process_message({'args': [], 'call': 4.946068198738698, 'name': 'u, <geventwebsocket.websocket.WebSocket object at 0x0)> failed with NameError

D:\Games\Graveyard Keeper\Graveyard Keeper Savefile Editor>"Graveyard Keeper Savefile Editor.exe"
Traceback (most recent call last):
  File "J:\Projekte\GitHub\Graveyard Keeper Savefile Editor\main.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "J:\Programme\Python64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "J:\Projekte\GitHub\Graveyard Keeper Savefile Editor\data\types.py", line 47, in <module>
  File "J:\Programme\Python64\lib\json\__init__.py", line 265, in load
  File "J:\Programme\Python64\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 20667: character maps to <undefined>
[9864] Failed to execute script main

**Comment by NetroScript** [comment]
Ah, I should have known this breaks it.

The new item names have utf-8 codes, the old version decoded it using the default of python, in the last commit I also added that it uses `utf-8` - but of course old versions of the editor don't have it. For now I will remove the item version and just ship it with a next bigger update.

You should be able to replace the html folder with the one in this zip:

https://github.com/NetroScript/Graveyard-Keeper-Savefile-Editor/archive/39fa084ecb748b02c5f39c0e8d8bbb9a32783db7.zip

(to fix the current editor)
