### ISSUE TITLE
Python 3.8.5 Eel 'options' argument deprecated

### ISSUE THREAD

**Issue by c1ph3rl1nux** [NetroScript/Graveyard-Keeper-Savefile-Editor#72]
Error Message:
```
Traceback (most recent call last):
  File "main.py", line 988, in <module>
    run()
  File "main.py", line 970, in run
    eel.start("no settings.html", options=web_app_options)
  File "/home/c1ph3rl1nux/.local/lib/python3.8/site-packages/eel/__init__.py", line 142, in start
    raise RuntimeError(api_error_message)
RuntimeError: 
----------------------------------------------------------------------------------
  'options' argument deprecated in v1.0.0, see https://github.com/ChrisKnott/Eel
  To suppress this error, add 'suppress_error=True' to start() call.
  This option will be removed in future versions

```
Proposed solution ( in main.py): 
```
    if os.path.isfile("./data/settings"):
        loadsettings()
        eel.start("loadsavefile.html", mode='chrome-app', port=0, chromeFlags=["--window-size=800,1000"])
    else:
        eel.start("no settings.html", mode='chrome-app', port=0, chromeFlags=["--window-size=800,1000"])

```

**Comment by NetroScript** [comment]
Considering people might also use older python / eel versions, I would rather do a check which eel version is used and depending on that, make different function calls.
