### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yobama3226** [NetroScript/Graveyard-Keeper-Savefile-Editor#91]
**Describe the bug**
I attempt to load one of my save games and it is unable to load it, even attempting to load the game without the editor results in a 
failed to load data error
**To Reproduce**

1. Go to Editor
2. Click on Save file
3. See error

**Expected behavior**
I expected the game to load my save file like it has been while I've been using it

**Screenshots**

**Please also add the following Information:**
* Most recent [0.1.24]
* Running the game and editor on Windows not the python version

Looking for save files in the folder: C:/Users/user/AppData/LocalLow/Lazy Bear Games/Graveyard Keeper
Found and loaded information for save: 1.info
Found and loaded information for save: 2.info
Beginning to decode file: C:/Users/user/AppData/LocalLow/Lazy Bear Games/Graveyard Keeper\2.dat
Extracting String Array
Extracting header
Extracting game objects
Error:
Traceback (most recent call last):
  File "S:\Projekte\GitHub\Graveyard Keeper Savefile Editor\main.py", line 179, in get_savefile
  File "S:\Projekte\GitHub\Graveyard Keeper Savefile Editor\data\decode.py", line 34, in decode
  File "S:\Projekte\GitHub\Graveyard Keeper Savefile Editor\data\decode.py", line 81, in deserialize
  File "S:\Projekte\GitHub\Graveyard Keeper Savefile Editor\data\decode.py", line 99, in deserializedata
  File "S:\Projekte\GitHub\Graveyard Keeper Savefile Editor\data\decode.py", line 81, in deserialize
  File "S:\Projekte\GitHub\Graveyard Keeper Savefile Editor\data\decode.py", line 161, in deserializedata
  File "S:\Projekte\GitHub\Graveyard Keeper Savefile Editor\data\decode.py", line 99, in deserializedata
  File "S:\Projekte\GitHub\Graveyard Keeper Savefile Editor\data\decode.py", line 81, in deserialize
  File "S:\Projekte\GitHub\Graveyard Keeper Savefile Editor\data\decode.py", line 107, in deserializedata
IndexError: list index out of range

**Comment by NetroScript** [comment]
Okay so for my understanding:

You are trying to load the second save file you have, and that error appears when loading it. 

>  even attempting to load the game without the editor results in a failed to load data error

And even when opening the save file within the game (2nd slot) the game also fails at opening the save file? 

If so following questions:

- Did you edit this save file previously with the editor?
- When did the game start failing to load the save file?
- Either when saving in the game, or with the editor, did the applications crash?

Assuming the game save worked before in game, but doesn't work now:

Both the game itself, and my editor (with standard settings) produce backup files before overwriting the old save file. 

The backup files of the game for your save would be called for example `2.dat.backup.1`. For my editor it would be called for example `2.dat.back_1.zip`.
It is then possible to use one of those previous backup files as they should load correctly.

For the backup files from the game you would need to rename it from `2.dat.backup.1` to `2.dat`, for my backup files you would need to unzip the save file and also rename it to `2.dat`.



----------------


If this is not the problem, I need some additional information, but I am just assuming that the previously described problem of a interrupted saving operation is the problem.
